# Generated by Django 4.1 on 2022-09-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cloud_cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_name', models.CharField(max_length=128, unique=True, verbose_name='集群名称')),
                ('auth_url', models.URLField(verbose_name='keystone认证地址')),
                ('username', models.CharField(max_length=128, verbose_name='用户名')),
                ('password', models.CharField(max_length=128, verbose_name='密码')),
                ('project_name', models.CharField(max_length=128, verbose_name='项目名称')),
                ('admin_password', models.CharField(max_length=128, verbose_name='管理员密码')),
                ('user_domain_name', models.CharField(default='default', max_length=128)),
                ('project_domain_name', models.CharField(default='default', max_length=128)),
                ('bk_idc_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.idc_info', verbose_name='机房')),
            ],
            options={
                'verbose_name': '集群管理',
                'verbose_name_plural': '集群管理',
            },
        ),
        migrations.CreateModel(
            name='cloud_vm_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='主机名')),
                ('server_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='虚拟机ID')),
                ('flavor', models.CharField(max_length=128, verbose_name='类型')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('status', models.CharField(default='BUILDING', max_length=32, verbose_name='状态')),
                ('compute', models.CharField(blank=True, max_length=64, null=True, verbose_name='宿主机')),
                ('date', models.DateField(blank=True, null=True, verbose_name='创建时间')),
                ('cluster_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='openstack.cloud_cluster')),
            ],
            options={
                'verbose_name': '云主机',
                'verbose_name_plural': '云主机',
            },
        ),
        migrations.CreateModel(
            name='cloud_network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='网络名称')),
                ('network_id', models.CharField(max_length=64, unique=True)),
                ('subnet', models.CharField(max_length=64, verbose_name='网段')),
                ('total_num', models.IntegerField(verbose_name='IP地址数量')),
                ('used_num', models.IntegerField(verbose_name='已使用IP地址数量')),
                ('free_num', models.IntegerField(verbose_name='空闲IP地址数量')),
                ('percent', models.IntegerField(verbose_name='使用率')),
                ('cluster_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='openstack.cloud_cluster')),
            ],
        ),
        migrations.CreateModel(
            name='cloud_flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flavor_name', models.CharField(max_length=64, verbose_name='模版名称')),
                ('flavor_id', models.CharField(max_length=64, unique=True, verbose_name='模版ID')),
                ('cluster_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='openstack.cloud_cluster')),
            ],
        ),
        migrations.CreateModel(
            name='cloud_compute_resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_ip', models.GenericIPAddressField(verbose_name='IP地址')),
                ('hypervisor_hostname', models.CharField(max_length=128, verbose_name='节点名称')),
                ('hypervisor_type', models.CharField(max_length=128, verbose_name='类型')),
                ('node_id', models.CharField(max_length=128, verbose_name='计算节点ID')),
                ('running_vms', models.IntegerField(verbose_name='虚拟机数量')),
                ('state', models.CharField(max_length=128, verbose_name='当前状态')),
                ('status', models.CharField(max_length=128, verbose_name='是否启用')),
                ('vcpus', models.IntegerField(verbose_name='vcpus数量')),
                ('vcpus_used', models.IntegerField(verbose_name='已使用vcpu')),
                ('vcpus_used_percent', models.IntegerField(verbose_name='vcpu超配比')),
                ('local_gb', models.IntegerField(verbose_name='磁盘')),
                ('local_gb_used', models.IntegerField(verbose_name='已使用磁盘')),
                ('local_gb_used_percent', models.IntegerField(verbose_name='磁盘使用率')),
                ('memory_mb', models.IntegerField(verbose_name='内存')),
                ('memory_mb_used', models.IntegerField(verbose_name='已使用内存')),
                ('memory_mb_used_percent', models.IntegerField(verbose_name='内存使用率')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='openstack.cloud_cluster', verbose_name='所属集群')),
            ],
        ),
    ]
