# Generated by Django 4.1 on 2022-09-02 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enname', models.CharField(max_length=30, null=True, unique=True, verbose_name='应用英文名')),
                ('cnname', models.CharField(max_length=30, null=True, verbose_name='应用中文名')),
                ('manager', models.CharField(max_length=30, null=True, verbose_name='负责人')),
            ],
            options={
                'verbose_name': '应用管理',
                'verbose_name_plural': '应用管理',
            },
        ),
        migrations.CreateModel(
            name='devgroup_name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='部门')),
            ],
            options={
                'verbose_name': '部门管理',
                'verbose_name_plural': '部门管理',
            },
        ),
        migrations.CreateModel(
            name='Envs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='环境名')),
            ],
            options={
                'verbose_name': '环境管理',
                'verbose_name_plural': '环境管理',
            },
        ),
        migrations.CreateModel(
            name='Idc_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='机房名称')),
                ('address', models.CharField(max_length=100, null=True, verbose_name='机房地址')),
                ('num', models.CharField(max_length=30, null=True, verbose_name='机房编号')),
            ],
            options={
                'verbose_name': '机房管理',
                'verbose_name_plural': '机房管理',
            },
        ),
        migrations.CreateModel(
            name='myPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='权限名称')),
                ('url', models.CharField(max_length=255, verbose_name='URL名称')),
                ('describe', models.CharField(max_length=255, verbose_name='描述')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
            },
        ),
        migrations.CreateModel(
            name='Server_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, null=True, unique=True, verbose_name='业务ip')),
                ('hostname', models.CharField(max_length=100, null=True, verbose_name='主机名')),
                ('managerip', models.CharField(max_length=30, null=True, unique=True, verbose_name='管理ip')),
                ('brand', models.CharField(max_length=30, null=True, verbose_name='机型')),
                ('hardware_parameters', models.CharField(max_length=30, null=True, verbose_name='硬件配置')),
                ('rittal', models.CharField(max_length=30, null=True, verbose_name='机柜')),
                ('u_site', models.CharField(max_length=30, null=True, verbose_name='U位')),
                ('sn', models.CharField(max_length=30, null=True, verbose_name='sn序列号')),
                ('buy_time', models.DateField(blank=True, null=True, verbose_name='购买时间')),
                ('expire_date', models.DateField(blank=True, null=True, verbose_name='过保时间')),
                ('app_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.app_info')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.envs')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.idc_info')),
            ],
            options={
                'verbose_name': '物理机管理',
                'verbose_name_plural': '物理机管理',
            },
        ),
        migrations.CreateModel(
            name='Server_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True, unique=True, verbose_name='状态名')),
            ],
            options={
                'verbose_name': '服务器状态管理',
                'verbose_name_plural': '服务器状态管理',
            },
        ),
        migrations.CreateModel(
            name='Vm_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, null=True, unique=True, verbose_name='ip')),
                ('hostname', models.CharField(max_length=100, null=True, verbose_name='主机名')),
                ('hardware_parameters', models.CharField(max_length=30, null=True, verbose_name='硬件配置')),
                ('system', models.CharField(max_length=30, null=True, verbose_name='操作系统')),
                ('app_info', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.app_info')),
                ('env', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.envs')),
                ('idc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.idc_info')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.server_info')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.server_status')),
            ],
            options={
                'verbose_name': '虚拟机管理',
                'verbose_name_plural': '虚拟机管理',
            },
        ),
        migrations.AddField(
            model_name='server_info',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.server_status'),
        ),
        migrations.CreateModel(
            name='Appdomain_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enname', models.CharField(max_length=30, null=True, unique=True, verbose_name='产品线英文名')),
                ('cnname', models.CharField(max_length=30, null=True, verbose_name='产品线中文名')),
                ('manager', models.CharField(max_length=30, null=True, verbose_name='负责人')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.devgroup_name')),
            ],
            options={
                'verbose_name': '产品线管理',
                'verbose_name_plural': '产品线管理',
            },
        ),
        migrations.AddField(
            model_name='app_info',
            name='appdomain_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.appdomain_info'),
        ),
    ]
