"""
Django settings for cmdb project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
env="dev"
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ku-ibb9o#cy-cmigy^9t+jx69yy$oghx8@to%aqxdz$k_)3%4r'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'core',
    'captcha',
    'openstack'

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'cmdb.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],

        'builtins' : [
                'django.templatetags.static'
            ],
        },
    },
]

WSGI_APPLICATION = 'cmdb.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases



if env == "prd":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',  # 默认用mysql
            'NAME': 'cmdb',                        # 数据库名 (默认与APP_ID相同)
            'USER': 'cmdb_user',                            # 你的数据库user
            'PASSWORD': 'OP2z7yNz6Y8rUyl6',                        # 你的数据库password
            'HOST': '10.250.132.117',                                   # 数据库HOST
            'PORT': '3306',                        # 默认3306
        },
}

elif env == "test":
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',  # 默认用mysql
            'NAME': 'cmdb',                        # 数据库名 (默认与APP_ID相同)
            'USER': 'root',                            # 你的数据库user
            'PASSWORD': '123456',                        # 你的数据库password
            'HOST': '127.0.0.1',                                   # 数据库HOST
            'PORT': '3306',                        # 默认3306
        },
    }

else:
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/



LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'


USE_I18N = True

USE_TZ = False



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
	os.path.join(BASE_DIR,"static")
]

# if DEBUG:
#     STATIC_PATH = os.path.join(BASE_DIR, 'static')
#     STATIC_URL = '/static/'
#     STATICFILES_DIRS = (STATIC_PATH,)
# else:
#     STATIC_ROOT = os.path.join(BASE_DIR, 'static')
#     STATIC_URL = '/static/'
# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#邮件参数配置
EMAIL_BACKEND ='django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.qq.com'
EMAIL_PORT = 25
EMAIL_HOST_USER = '1083559808@qq.com'
EMAIL_HOST_PASSWORD = 'tobbnlzyszfebaff'

# 注册有效期天数
CONFIRM_DAYS = 2




X_FRAME_OPTIONS = 'SAMEORIGIN'
SECURE_CROSS_ORIGIN_OPENER_POLICY = None

